"""add sd chat

Revision ID: 7ef8acba45b0
Revises: 4b984c00cc56
Create Date: 2026-09-21 20:01:05.943912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef8acba45b0'
down_revision: Union[str, Sequence[str], None] = '4b984c00cc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('audience_type', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('requires_acknowledgement', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_announcements_audience_type'), 'chat_announcements', ['audience_type'], unique=False)
    op.create_index(op.f('ix_chat_announcements_author_user_id'), 'chat_announcements', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_chat_announcements_created_at'), 'chat_announcements', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_announcements_department_id'), 'chat_announcements', ['department_id'], unique=False)
    op.create_index(op.f('ix_chat_announcements_expires_at'), 'chat_announcements', ['expires_at'], unique=False)
    op.create_index(op.f('ix_chat_announcements_is_active'), 'chat_announcements', ['is_active'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_conversation_type'), 'chat_conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_chat_conversations_created_at'), 'chat_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_conversations_created_by_user_id'), 'chat_conversations', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_updated_at'), 'chat_conversations', ['updated_at'], unique=False)
    op.create_table('chat_announcement_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['chat_announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_chat_announcement_recipient')
    )
    op.create_index(op.f('ix_chat_announcement_recipients_announcement_id'), 'chat_announcement_recipients', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_chat_announcement_recipients_user_id'), 'chat_announcement_recipients', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_message_type'), 'chat_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_user_id'), 'chat_messages', ['sender_user_id'], unique=False)
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'],['chat_messages.id'],ondelete='SET NULL',),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_chat_participant')
    )
    op.create_index(op.f('ix_chat_participants_conversation_id'), 'chat_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_participants_last_read_message_id'), 'chat_participants', ['last_read_message_id'], unique=False)
    op.create_index(op.f('ix_chat_participants_user_id'), 'chat_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_participants_user_id'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_last_read_message_id'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_conversation_id'), table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index(op.f('ix_chat_messages_sender_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_message_type'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_announcement_recipients_user_id'), table_name='chat_announcement_recipients')
    op.drop_index(op.f('ix_chat_announcement_recipients_announcement_id'), table_name='chat_announcement_recipients')
    op.drop_table('chat_announcement_recipients')
    op.drop_index(op.f('ix_chat_conversations_updated_at'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_created_by_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_created_at'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_conversation_type'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_chat_announcements_is_active'), table_name='chat_announcements')
    op.drop_index(op.f('ix_chat_announcements_expires_at'), table_name='chat_announcements')
    op.drop_index(op.f('ix_chat_announcements_department_id'), table_name='chat_announcements')
    op.drop_index(op.f('ix_chat_announcements_created_at'), table_name='chat_announcements')
    op.drop_index(op.f('ix_chat_announcements_author_user_id'), table_name='chat_announcements')
    op.drop_index(op.f('ix_chat_announcements_audience_type'), table_name='chat_announcements')
    op.drop_table('chat_announcements')
    # ### end Alembic commands ###
